-- public.cliente definition

-- Drop table

-- DROP TABLE cliente;

CREATE TABLE cliente (
	idcliente int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar NOT NULL,
	nome varchar NOT NULL,
	CONSTRAINT cliente_pk PRIMARY KEY (idcliente),
	CONSTRAINT cliente_un UNIQUE (email)
);


-- public.cotacaocripto definition

-- Drop table

-- DROP TABLE cotacaocripto;

CREATE TABLE cotacaocripto (
	codcripto varchar(5) NOT NULL,
	nomecripto varchar NOT NULL,
	cotacaoreal numeric(20, 2) NOT NULL,
	CONSTRAINT cotacaocripto_pk PRIMARY KEY (codcripto)
);


-- public.pagamento definition

-- Drop table

-- DROP TABLE pagamento;

CREATE TABLE pagamento (
	idpagamento int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar NOT NULL,
	CONSTRAINT pagamento_pk PRIMARY KEY (idpagamento)
);


-- public.produto definition

-- Drop table

-- DROP TABLE produto;

CREATE TABLE produto (
	idproduto int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nomeproduto varchar NOT NULL,
	categoria varchar NOT NULL,
	descricao text NULL DEFAULT ''::text,
	especificacoes json NULL,
	precoreal numeric(20, 2) NOT NULL,
	CONSTRAINT produto_pk PRIMARY KEY (idproduto)
);


-- public.avaliacao definition

-- Drop table

-- DROP TABLE avaliacao;

CREATE TABLE avaliacao (
	idcliente int4 NOT NULL,
	idproduto int4 NOT NULL,
	recomendado bool NOT NULL,
	descricao varchar NULL,
	CONSTRAINT avaliacao_pkey PRIMARY KEY (idcliente, idproduto),
	CONSTRAINT avaliacao_idcliente_fkey FOREIGN KEY (idcliente) REFERENCES cliente(idcliente),
	CONSTRAINT avaliacao_idproduto_fkey FOREIGN KEY (idproduto) REFERENCES produto(idproduto)
);


-- public.endereco definition

-- Drop table

-- DROP TABLE endereco;

CREATE TABLE endereco (
	idcliente int4 NOT NULL,
	cep bpchar(9) NOT NULL,
	logradouro varchar NOT NULL,
	numero int4 NOT NULL,
	complemento varchar NULL,
	bairro varchar NOT NULL,
	cidade varchar NOT NULL,
	estado bpchar(2) NOT NULL,
	CONSTRAINT endereco_pkey PRIMARY KEY (idcliente),
	CONSTRAINT endereco_idcliente_fkey FOREIGN KEY (idcliente) REFERENCES cliente(idcliente)
);


-- public.pagamentocliente definition

-- Drop table

-- DROP TABLE pagamentocliente;

CREATE TABLE pagamentocliente (
	idcliente int4 NOT NULL,
	idpagamento int2 NOT NULL,
	dadospagamento json NOT NULL,
	CONSTRAINT pagamentocliente_pkey PRIMARY KEY (idcliente, idpagamento),
	CONSTRAINT pagamentocliente_idcliente_fkey FOREIGN KEY (idcliente) REFERENCES cliente(idcliente),
	CONSTRAINT pagamentocliente_idpagamento_fkey FOREIGN KEY (idpagamento) REFERENCES pagamento(idpagamento) ON DELETE CASCADE
);


-- public.pedido definition

-- Drop table

-- DROP TABLE pedido;

CREATE TABLE pedido (
	numpedido int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	datapedido date NULL DEFAULT CURRENT_DATE,
	idcliente int4 NOT NULL,
	cepenvio bpchar(9) NOT NULL,
	enderecoenvio text NOT NULL,
	moeda varchar(5) NULL DEFAULT 'BRL'::bpchar,
	formapagamento varchar NOT NULL,
	dadospagamento json NOT NULL,
	CONSTRAINT pedido_pk PRIMARY KEY (numpedido),
	CONSTRAINT pedido_fk FOREIGN KEY (idcliente) REFERENCES cliente(idcliente)
);


-- public.produtopedido definition

-- Drop table

-- DROP TABLE produtopedido;

CREATE TABLE produtopedido (
	numpedido int8 NOT NULL,
	idproduto int4 NOT NULL,
	precounitario numeric(20, 8) NOT NULL,
	quantidade int2 NULL DEFAULT 1,
	CONSTRAINT produtopedido_pk PRIMARY KEY (numpedido, idproduto),
	CONSTRAINT produtopedido_fk FOREIGN KEY (numpedido) REFERENCES pedido(numpedido),
	CONSTRAINT produtopedido_fk_1 FOREIGN KEY (idproduto) REFERENCES produto(idproduto)
);